Unifies the es_failure flow
Automattic/vip-go-mu-plugins pull request #1825
Opened 2020-10-22 19:02 UTC by pschoffer

## Description

Unifies the es_failure flow

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

The change is covered in unittests as it depends on external API to fail, which is difficult to fake.

2020-11-02 17:22 UTC, brandon-m-skinner requested changes
Looks good, just some minor whitespace changes to keep the same style.

2020-11-02 17:22 UTC, brandon-m-skinner commented on search/includes/classes/class-search.php
> +			$this->ep_handle_failed_request( $response, $statsd_prefix );
```suggestion
		if ( is_wp_error( $response ) || $response_code >= 400 ) {
			$this->ep_handle_failed_request( $response, $statsd_prefix );
```

2020-11-02 17:22 UTC, brandon-m-skinner commented on search/includes/classes/class-search.php
```suggestion
```

2020-11-03 08:27 UTC, pschoffer commented
Sweet thanks for looking into it!

2020-11-09 18:17 UTC, brandon-m-skinner approved these changes

2020-11-10 13:05 UTC, merged

2020-11-10 13:07 UTC, pschoffer commented
Stacks-r1259