vip-plugins: "VIP Featured Plugins" -> "VIP Featured Partners"
Automattic/vip-go-mu-plugins pull request #1856
Opened 2020-11-13 21:22 UTC by curtisbelt

2020-11-14 12:01 UTC, GaryJones commented on vip-plugins/vip-plugins.php
> +			<p><?php _e( 'Unable to display VIP featured partners; try refreshing this page in a few minutes. If this error persists, please contact VIP Support.', 'vip-plugins-dashboard' ); ?></p>
```suggestion
			<p><?php esc_html_e( 'Unable to display VIP featured partners; try refreshing this page in a few minutes. If this error persists, please contact VIP Support.', 'vip-plugins-dashboard' ); ?></p>
```

2020-11-14 12:01 UTC, GaryJones commented on vip-plugins/vip-plugins.php
> +		<h3><?php _e( 'VIP Featured Partners', 'vip-plugins-dashboard' ); ?></h3>
```suggestion
		<h3><?php esc_html_e( 'VIP Featured Partners', 'vip-plugins-dashboard' ); ?></h3>
```

2020-11-17 15:32 UTC, brandon-m-skinner commented
I think the name should be something like VIP Technology Partner Plugins. Thoughts?

2020-11-17 15:48 UTC, ryansholin commented
:wave: VIP "Featured Technology Partners" is correct, thanks! (Not all partners have plugins; not all partners are featured; this is intentional.)

2020-11-17 15:57 UTC, brandon-m-skinner approved these changes

2020-11-17 15:59 UTC, brandon-m-skinner requested changes
Added Technology to the title as per @ryansholin s comment.

2020-11-17 15:59 UTC, brandon-m-skinner commented on vip-plugins/vip-plugins.php
> +			<p><?php esc_html_e( 'Unable to display VIP featured partners; try refreshing this page in a few minutes. If this error persists, please contact VIP Support.', 'vip-plugins-dashboard' ); ?></p>
```suggestion
			<p><?php esc_html_e( 'Unable to display VIP Featured Technology Partners; try refreshing this page in a few minutes. If this error persists, please contact VIP Support.', 'vip-plugins-dashboard' ); ?></p>
```

2020-11-17 15:59 UTC, brandon-m-skinner commented on vip-plugins/vip-plugins.php
> +		<h3><?php esc_html_e( 'VIP Featured Partners', 'vip-plugins-dashboard' ); ?></h3>
```suggestion
		<h3><?php esc_html_e( 'VIP Featured Technology Partners', 'vip-plugins-dashboard' ); ?></h3>
```

2020-11-17 16:02 UTC, brandon-m-skinner approved these changes

2020-11-17 17:31 UTC, merged

2020-11-17 17:35 UTC, brandon-m-skinner commented
r1269-stacks