Trigger a warning for prolonged rate limiting
Automattic/vip-go-mu-plugins pull request #1863
Opened 2020-11-17 02:26 UTC by brandon-m-skinner

## Description

Presently we just push the messages to Slack. We should also trigger a warning so functionality built around that can pick it up and put it where it needs to be.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

1. Set the rate limiting thresholds for Search queries and indexing low.
2. Trigger ratelimiting. There should be no warning generated.
3. Apply PR.
4. Trigger ratelimiting. A warning should be generated.

2020-11-17 18:23 UTC, nickdaugherty commented on search/includes/classes/class-queue.php
> +			'Application %d - %s has had it\'s Elasticsearch indexing rate limited for %d seconds. Large batch indexing operations are being queued for indexing in batches over time.',
```suggestion
			'Application %d - %s has had its Elasticsearch indexing rate limited for %d seconds. Large batch indexing operations are being queued for indexing in batches over time.',
```

2020-11-17 18:23 UTC, nickdaugherty commented on search/includes/classes/class-search.php
> +			'Application %d - %s has had it\'s Elasticsearch queries rate limited for %d seconds. Half of traffic is diverted to the database when queries are rate limited.',
```suggestion
			'Application %d - %s has had its Elasticsearch queries rate limited for %d seconds. Half of traffic is diverted to the database when queries are rate limited.',
```

2020-11-17 18:26 UTC, nickdaugherty commented on tests/search/test-class-search.php
> +		@$es->maybe_alert_for_prolonged_query_limiting();
PHPUnit can be told to expect exceptions (which is what eventually happens when the called code triggers an error) - that has the benefit of not using error supression but also asserting that the warning is created:

https://github.com/Automattic/vip-go-mu-plugins/blob/429dc63cffdf82fdbc9f663ce904fb10e09a46b0/tests/search/test-class-search.php#L1267-L1268

2020-11-17 18:26 UTC, nickdaugherty requested changes
Looks good, just noted a few small things.

2020-11-19 16:28 UTC, nickdaugherty approved these changes

2020-11-19 19:03 UTC, netsuso approved these changes

2020-11-19 19:03 UTC, merged

2020-11-19 19:05 UTC, netsuso commented
stacks-r1280