Search: Add result compression
Automattic/vip-go-mu-plugins pull request #2004
Opened 2021-03-01 14:35 UTC by pschoffer

## Description

## Changelog Description

### Plugin Updated: Search

This change enables compression on HTTP requests towards Elastic Search.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples. 

## Steps to Test
1. Add a debug line `var_dump(['Response headers', $response['headers'] ]);`
2. Do any ES request e.g. `wp vip-search documents get post 1`
3. See the headers - `'content-encoding'` is not there
4. Apply the PR
5.  Do any ES request e.g. `wp vip-search documents get post 1`
6. Verify `'content-encoding'` header is present

2021-03-01 15:26 UTC, rinatkhaziev requested changes
Thanks for the PR, had no idea we don't do this already :)

Unfortunately `libcurl` we use is not compiled with brotli support, so let's swap that out to what we currently support.

2021-03-01 15:26 UTC, rinatkhaziev commented on search/includes/classes/class-search.php
> +				'Accept-Encoding' => 'gzip, br',
```suggestion
				'Accept-Encoding' => 'gzip, deflate',
```

Brotli is currently not supported by the libcurl version we use:

```
curl --compressed https://httpbin.org/brotli
curl: (61) Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
```

2021-03-01 15:40 UTC, pschoffer commented
Cool catch!

2021-03-01 15:48 UTC, rinatkhaziev approved these changes
:shipit:

2021-03-01 22:59 UTC, nickdaugherty approved these changes

2021-03-01 23:01 UTC, merged

2021-03-01 23:10 UTC, nickdaugherty commented
r1416-stacks

2021-03-01 23:14 UTC, nickdaugherty commented
@pschoffer I deployed this to staging, but i'm not 100% sure it's working as I'm not seeing the new header in requests when viewed through Debug Bar. It could be that it's a debug bar thing, but worth double checking.

2021-03-02 10:40 UTC, pschoffer commented
I double checked today. It does seem to work when I print out headers directly in code. I got:
```
 string 'HTTP/1.1 200 OK
Server: nginx
Date: Tue, 02 Mar 2021 10:33:09 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Content-Encoding: gzip
```

So that looks good. I still see only a subset of the request headers without the `Accept-Encoding` among others. So I guess it is filtered somewhere in debug bar.

2021-03-02 17:43 UTC, nickdaugherty commented
Great, thanks for checking @pschoffer !