Merge 'add/local-vip-go-env-const'...
Automattic/vip-go-mu-plugins pull request #2005
Opened 2021-03-01 17:05 UTC by seanosh

## Description

When setting up a local development environment that utilizes `vip-go-mu-plugins`, it's helpful to enable debug bar and relevant tooling. Setting `WPCOM_IS_VIP_ENV` to `false` is correct for a local environment, but doesn't offer a way to selectively enable something like debug tooling. 

I went with this approach because other logic for enabling mostly revolves around things specific to the platform (employee, proxy status) that would require additional/riskier changes or inclusion of hooks/filters at the onset locally, which isn't as "clean" as defining constant for storing environment type. 

cc: @joshbetz (thanks for being a sounding board on this!)

## Changelog Description

### Add support for VIP_GO_ENV to be set to 'local' in order to enable debug tooling in local environments

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples. 

## Steps to Test
1. Check out and apply PR in local environment
2. Add to `wp-config.php`:
```
define( 'WPCOM_IS_VIP_ENV', false );
define( 'VIP_GO_ENV', 'local' );
define( 'VIP_BLOCK_WP_MAIL', true );
define( 'FILES_CLIENT_SITE_ID', 1 );
```
3. Visit local environment URL without having logged in and observe debug panel presence.

2021-03-01 17:09 UTC, mjangda commented
Might be better to set and check `'local' === WP_ENVIRONMENT_TYPE`? (https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/)

A non-false value for VIP_GO_ENV might have other unintended consequences.

2021-03-01 17:46 UTC, seanosh commented
Nice, thanks @mjangda - updated the PR accordingly.

2021-03-01 17:49 UTC, rinatkhaziev commented
To really make it magical we also need to define the `local` in this block: 

https://github.com/Automattic/vip-go-mu-plugins/blob/02729f0e4f23c72dee12d2b2208d9b2384e42fd7/000-vip-init.php#L208-L224

2021-03-01 18:18 UTC, rinatkhaziev requested changes
Thanks for the addition @seanosh, left a suggestion.

2021-03-01 18:18 UTC, rinatkhaziev commented on 000-debug/debug-mode.php
> +	$is_local = ( ( defined( 'WP_ENVIRONMENT_TYPE' ) && 'local' === WP_ENVIRONMENT_TYPE ) ? true : false );
```suggestion
	$is_local = defined( 'WP_ENVIRONMENT_TYPE' ) && 'local' === WP_ENVIRONMENT_TYPE;
```

2021-03-01 18:18 UTC, rinatkhaziev commented on 000-debug/debug-mode.php
> +	$is_local = ( ( defined( 'WP_ENVIRONMENT_TYPE' ) && 'local' === WP_ENVIRONMENT_TYPE ) ? true : false );
The ternary is redundant here.

2021-03-01 18:26 UTC, rinatkhaziev approved these changes

2021-03-01 18:29 UTC, rinatkhaziev commented
Updated changelog entry

2021-03-16 16:56 UTC, merged

2021-03-16 16:58 UTC, nickdaugherty commented
r1443-stacks

2021-03-16 19:00 UTC, nickdaugherty commented
Release v1.22.0