Remove Gutenberg Ramp completely
Automattic/vip-go-mu-plugins pull request #2075
Opened 2021-04-19 12:26 UTC by gudmdharalds

We are aiming to remove the Gutenberg Ramp plugin. This is the last step in this process. Previous PRs are #1986 and #1958, #2039, #2045, #2064 and #2069.

This PR was submitted as #1992 previously but due to conflicts that cannot be solved a new one had to be opened.

This Pull-Request will remove the Gutenberg Ramp plugin from the `vip-go-mu-plugins` repository, and thus remove the plugin from the VIP Go Platform completely. We have taken steps to remove any invocations to the plugin by submitting Pull-Requests. In some cases Gutenberg Ramp will live in individual repositories, but that is independent from this Pull-Request.

This Pull-Request can be merged when suitable for Platform.

## Changelog Description

### Plugin Removed: Gutenberg Ramp

We completely removed the `gutenberg-ramp` submodule and also the `gutenberg-ramp.php` file from `vip-go-mu-plugins` as the plugin is deprecated and should no longer be used. We've taken steps to ensure that this action will not be disruptive.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [N/A] This change works and has been tested locally (or has an appropriate fallback).
- [-] This change works and has been tested on a Go sandbox. - Yes, multiple, and with multiple configurations of filters.
- [N/A] This change has relevant unit tests (if applicable).
- [N/A] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples. 

## Steps to Test

1. Start a VIP Go sandbox for a site. Make note of what editor is loaded currently for a particular post type, Classic or Gutenberg.
2. Check out the Pull-Request on a local VIP Go sandbox: https://patch-diff.githubusercontent.com/raw/Automattic/vip-go-mu-plugins/pull/1992.diff
3. Observe that the `gutenberg-ramp` plugin is not deployed and same with the `gutenberg-ramp.php` file.
4. Make sure the current site works, both front-page and `wp-admin`.
5. Make sure editor functionality remains same as before.

2021-04-20 02:54 UTC, rinatkhaziev submitted a review, later dismissed
This is exciting!

Could you also please remove the corresponding feature flag definition from the Feature lib?

2021-04-20 12:10 UTC, gudmdharalds commented
> Could you also please remove the corresponding feature flag definition from the Feature lib?

Of course! Sorry, I forgot about it. Now done in 4b182fa.

2021-04-21 08:31 UTC, pauarge requested changes
Nice work! There is also a reference to `gutenberg-ramp` in `phpcs.xml.dist`, I think that could be removed as well.

2021-04-21 10:37 UTC, pauarge approved these changes

2021-04-22 11:08 UTC, merged