File Service: implement handling of the read-only mode both for core methods and lower-level streamWrapper implementation
Automattic/vip-go-mu-plugins pull request #2109
Opened 2021-05-06 18:52 UTC by rinatkhaziev

## Description

In preparation to the File Service maintenance window, this PR aims to implement additional safeguards and better error messaging should any upload be tried during the said window.

This should both cover core WordPress upload functions as well as lower-level streamWrapper implementation. E.g. `fopen( 'vip://wp-content/uploads/new-file.txt', 'w' )`

The behavior is changed in the following way:

If an upload is made during the read-only period via WP Admin UI a user will be presented with an error `'Uploads are temporarily disabled due to Files service maintenance. Please try again later.`

If the code tries to open a file with `fopen`, in case the file doesn't exist, instead of trying to create a temporary handle an E_USER_WARNING is emitted, and `false` gets returned instead of the `resource`

**NB:** For the lower-level part to work a special constant `FILE_SERVICE_WRITES_DISABLED` must be defined and set to `true`.

## Changelog Description

### Update: File Service integration

Better handling of attempted uploads during a read-only period for upcoming maintenance on May 10.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

2021-05-07 07:13 UTC, pauarge requested changes
Changes look good, but could we add a couple of unit tests to check them?

2021-05-10 11:06 UTC, pauarge approved these changes
LGTM

2021-05-10 16:36 UTC, pauarge approved these changes

2021-05-10 18:34 UTC, merged

2021-05-10 18:36 UTC, rinatkhaziev commented
r1542-stacks