Files: remove legacy code for handling media uploads
Automattic/vip-go-mu-plugins pull request #2185
Opened 2021-06-05 02:53 UTC by rinatkhaziev

## Description

We had quite a few lines of cruft/dead code, it's time to say goodbye to it.

- This supersedes #1012 (Globally enable Photon's local filters)
- Removes VIP Legacy Filesystem implementation.

This needs quite a bit of manual testing.

## Changelog Description

### Files: remove legacy code

We've removed all legacy code related to previous iterations of media implementation.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out PR.
1. Test uploads locally
1. Test uploads on a sandbox
1. Verify resizing works as expected.

2021-06-08 15:32 UTC, mjangda commented
Two thoughts:

- We should do a quick scan to see if any of the functions being removed are being used directly in customer code. Technically, that would be `_doing_it_wrong` since a8c-files was never meant as a public API but the code has been around since the early days and it was the wild west back then :)
- The Photon changes should be in a separate PR.

2021-06-08 15:49 UTC, rinatkhaziev commented
> The Photon changes should be in a separate PR.

@mjangda I'm not sure I agree, both of the changes fit in the same scope of un-crufting a8c-files.php implementation. If you insist, I can do that though :)

2021-06-08 15:59 UTC, mjangda commented
Are all sites using Jetpack Photon filters now? If not, we're introducing a functional change, and not just removing cruft.

2021-06-08 16:32 UTC, rinatkhaziev commented
@mjangda fair point.

2021-06-09 17:09 UTC, rinatkhaziev commented
@mjangda I reverted the Photon part, this should limit the potential blast radius

2021-06-11 20:07 UTC, mjangda reviewed
Spotted a few small things.

2021-06-11 20:07 UTC, mjangda commented on a8c-files.php
>  		if ( defined( 'VIP_FILESYSTEM_USE_STREAM_WRAPPER' ) && true === VIP_FILESYSTEM_USE_STREAM_WRAPPER ) {
I guess we need it for local compat?

2021-06-11 20:07 UTC, mjangda commented on a8c-files.php
>  	function get_files_service_hostname() {
If we remove `attachment_file_exists`, I believe this can be removed as well?

2021-08-04 13:38 UTC, pauarge commented on a8c-files.php
>  	function attachment_file_exists( $file_url ) {
👍

2021-08-04 13:39 UTC, pauarge requested changes
Looks good to me except from the couple of functions that can be removed that Mo already mentioned.

2021-08-05 18:06 UTC, rinatkhaziev commented on a8c-files.php
>  		if ( defined( 'VIP_FILESYSTEM_USE_STREAM_WRAPPER' ) && true === VIP_FILESYSTEM_USE_STREAM_WRAPPER ) {
I think so?

2021-08-05 18:27 UTC, pauarge approved these changes
LGTM

2021-08-16 17:56 UTC, merged

2021-08-16 17:58 UTC, rinatkhaziev commented
r1759-stacks