Check if Jetpack Stats module is active when using VIP Stats
Automattic/vip-go-mu-plugins pull request #2266
Opened 2021-07-02 23:05 UTC by raamdev

## Description

The VIP Stats functions `wpcom_vip_top_posts_array()` and `wpcom_vip_get_post_pageviews()` produce the following PHP fatal error when the Jetpack Stats module has been programmatically disabled:

```
PHP Fatal error:  Uncaught Error: Call to undefined function stats_get_csv() in /var/www/wp-content/mu-plugins/vip-helpers/vip-stats.php:41
```

This PR resolves this error by checking if the Jetpack Stats module is active before using the Jetpack Stats function `stats_get_csv()` and supplies a [`_doing_it_wrong()`](https://developer.wordpress.org/reference/functions/_doing_it_wrong/) message to clarify that these functions expect the Jetpack Stats module to be active.

## Changelog Description
### Check if the Jetpack Stats module is active when using VIP Stats

Improves error handling in VIP Stats functions `wpcom_vip_top_posts_array()` and `wpcom_vip_get_post_pageviews()` by checking if the Jetpack Stats module is active.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- N/A - This change has relevant unit tests (if applicable).
- N/A - This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Before applying this patch,  programmatically disable the Jetpack Stats module and then use `wpcom_vip_top_posts_array()` or `wpcom_vip_get_post_pageviews()`. The following code snippet can be added to an MU plugin for testing:

```php
<?php
// Disable the Stats Jetpack Module
function disable_jetpack_modules( $modules ) {
	$disabled_modules = ['stats'];

	foreach ( $disabled_modules as $module_slug ) {
		$found = array_search( $module_slug, $modules, true );
		if ( false !== $found ) {
			unset( $modules[ $found ] );
		}
	}
	return $modules;
}
add_filter( 'jetpack_active_modules', 'disable_jetpack_modules', 99, 9 );

// Use wpcom_vip_get_post_pageviews() to show Post Views at the bottom of Single Posts content
function filter_the_content_in_the_main_loop( $content ) {
    if ( is_singular() && in_the_loop() && is_main_query() ) {
        return $content . esc_html__( 'Post Views: ' . wpcom_vip_get_post_pageviews( get_the_ID(), 1 ) );
    }

    return $content;
}
add_filter( 'the_content', 'filter_the_content_in_the_main_loop', 1 );
```
2. Verify that this PHP Fatal error is thrown when viewing a single post:
```
PHP Fatal error:  Uncaught Error: Call to undefined function stats_get_csv()
```
3. Apply the patch in this PR and verify that the error is no longer thrown (the functions silently fall back to using fake data as expected).

2021-07-06 02:45 UTC, WPprodigy reviewed
The fallback logic in both of these functions that "fake the data returned" seem undesirable in any production scenario.

Should we just always log this as an error (so drop the new conditional)? Also of note `_doing_it_wrong()` seems to only trigger an `E_USER_NOTICE` when WP_DEBUG is active. So we wouldn't get these in logstash either.

I think maybe it should be a WARNING on any live environment. Maybe even further down the road we should deprecate this fallback logic and have it throw an error/null-type value instead of mocking for non-local situations.

2021-07-22 21:18 UTC, GaryJones requested changes

2021-07-22 21:18 UTC, GaryJones commented on vip-helpers/vip-stats.php
> +			_doing_it_wrong( __FUNCTION__, esc_html__( 'The Jetpack Stats module is disabled but used by VIP Stats.' ), '0.1' );
I don't think _doing_it_wrong() is the right approach here - the calling code for the VIP function is correct, but some other condition at runtime (the Stats module being enabled) is not correct. 

See the description of https://developer.wordpress.org/reference/functions/_doing_it_wrong/ for the intent. 

You wouldn't call _doing_it_wrong() when a MySQLi function was correctly called, but the DB was offline.

2021-07-22 21:18 UTC, GaryJones commented on vip-helpers/vip-stats.php
> +			_doing_it_wrong( __FUNCTION__, esc_html__( 'The Jetpack Stats module is disabled but used by VIP Stats.' ), '0.1' );
As above.

2021-07-23 16:05 UTC, raamdev commented
Thanks for the feedback @WPprodigy @GaryJones. 

@pauarge has opened a new PR to address those concerns in https://github.com/Automattic/vip-go-mu-plugins/pull/2306, so I'm closing this PR in favor of that one.

2021-07-23 16:05 UTC, closed without merging