Fix/fake data vip stats
Automattic/vip-go-mu-plugins pull request #2306
Opened 2021-07-23 14:42 UTC by pauarge

## Description

## Changelog Description

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

2021-07-23 15:46 UTC, raamdev approved these changes
This looks good to me. 

I just wanted to leave a note here to clarify that after this change is released, anyone using `wpcom_vip_top_posts_array()` who has Jetpack disabled or the Jetpack Stats module disabled will go from seeing real posts returned (but fake 'top posts' data) to seeing nothing returned, which may be slightly unexpected (e.g., may result in Top Posts widgets being empty). 

That said, I agree that returning nothing and triggering an error to clarify that the function is not intended to work without Jetpack makes more sense than silently returning fake data and having the problem go unnoticed, which is the case before this change.

2021-07-24 00:47 UTC, GaryJones requested changes
Minor suggested tweaks of the error message. Good otherwise.

2021-07-24 00:47 UTC, GaryJones commented on vip-helpers/vip-stats.php
> +		trigger_error( 'Cannot call wpcom_vip_top_posts_array without both Jetpack and the Jetpack Stats module active.', E_USER_WARNING );
```suggestion
		trigger_error( 'Cannot call wpcom_vip_top_posts_array() without both Jetpack and the Jetpack Stats module active.', E_USER_WARNING );
```

2021-07-24 00:47 UTC, GaryJones commented on vip-helpers/vip-stats.php
> +		trigger_error( 'Cannot call wpcom_vip_get_post_pageviews without both Jetpack and the Jetpack Stats module active.', E_USER_WARNING );
```suggestion
		trigger_error( 'Cannot call wpcom_vip_get_post_pageviews() without both Jetpack and the Jetpack Stats module active.', E_USER_WARNING );
```

2021-07-29 15:00 UTC, GaryJones approved these changes

2021-07-30 07:31 UTC, merged