Adding stale bot
Automattic/vip-go-mu-plugins pull request #2334
Opened 2021-08-06 14:18 UTC by pauarge

## Description

## Changelog Description

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

2021-08-06 14:29 UTC, rinatkhaziev requested changes
Looks good! I left a couple of minor wording suggestions, plus let's be less stringent for now (warn after 90 days and close after 14) - we can always bump it down.

2021-08-06 14:29 UTC, rinatkhaziev commented on .github/.stale
> +daysUntilStale: 60
```suggestion
daysUntilStale: 90
```

2021-08-06 14:29 UTC, rinatkhaziev commented on .github/.stale
> +daysUntilClose: 7
```suggestion
daysUntilClose: 14
```

2021-08-06 14:29 UTC, rinatkhaziev commented on .github/.stale
> +  recent activity in the past 60 days. It will be closed in 7 days if no
```suggestion
  recent activity in the past 90 days. It will be closed in 14 days if no
```

2021-08-06 14:29 UTC, rinatkhaziev commented on .github/.stale
> +  further activity occurs. Thank you for your contributions.
```suggestion
  further activity occurs. Thank you for your contribution.
  
  Please feel free to re-open and address the feedback and we'll take another look.
```

2021-08-09 05:30 UTC, pschoffer commented
Thank you @pauarge !

2021-08-09 11:05 UTC, pschoffer approved these changes

2021-08-09 17:57 UTC, merged