Search: query ES for the last post ID in get_last_post_id()
Automattic/vip-go-mu-plugins pull request #2644
Opened 2021-11-22 19:47 UTC by rebeccahum

## Description
`get_last_post_id()` only queries the DB for the last post ID, which means if we have an extra post in the ES index, our `validate-contents` will not include it in the range and therefore, it will be missed.

## Changelog Description
### Plugin Updated: Enterprise Search

Fix bug where `get_last_post_id()` doesn't account for extra ID in ES index.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test
0. Check out PR
1. Create a post - `vip dev-env --slug test exec -- wp post create --post_title=test --post_status=publish`
2. Delete the created post directly in DB - `vip dev-env --slug test exec -- wp db cli + DELETE FROM wp_posts WHERE ID = 50;`
3. Flush the cache - `vip dev-env --slug test exec -- wp cache flush`
4. Run `dev-env exec --slug test -- wp vip-search health validate-contents`

You should see the last post in ES in the range. For this example, we are using `50`:

```
Validating posts 1 - 50...✘ (attempted to reconcile)
```

2021-11-22 22:43 UTC, rinatkhaziev commented on search/includes/classes/class-health.php
> +				'orderby'        => 'ID',
I think it's better to be explicit here.

```suggestion
				'orderby'        => 'ID',
				'order'        => 'desc',
```

2021-11-22 22:45 UTC, rinatkhaziev requested changes
Nice catch! It'd be good to add PHPDoc for the method that would state that this both checks DB and ES last post ID.

2021-11-23 00:04 UTC, brandon-m-skinner commented
I think the underlying issue around figuring out if an ES index has posts beyond the current last post ID should be resolved another way or the function should be renamed. The database is the source of truth in this case and having a function called `get_last_post_id` that may return a post ID outside of what the source of truth says is inconsistent with what would be expected. Can end up with some interesting bugs if someone uses it outside of this specific use case with the expectation that the returned ID is linked to an existing fetchable post.

2021-11-23 02:23 UTC, rebeccahum commented
OK, I've split it into `get_last_db_post_id()` and `get_last_es_post_id()` so the user will explicitly use `get_last_db_post_id()` if they are expecting the DB to be the source of truth.

2021-11-24 13:18 UTC, rinatkhaziev approved these changes

2021-11-24 17:25 UTC, merged

2021-11-24 17:28 UTC, rebeccahum commented
r2042-stacks