Use PHP 8.0 for linting
Automattic/vip-go-mu-plugins pull request #3108
Opened 2022-04-28 15:26 UTC by sjinks

2022-04-28 16:15 UTC, jesse-greathouse submitted a review, later dismissed

2022-04-28 17:47 UTC, rinatkhaziev requested changes

2022-04-28 17:47 UTC, rinatkhaziev commented on .circleci/config.yml
>    php74-lint:
Probably should update here.

2022-04-28 17:51 UTC, sjinks commented on .circleci/config.yml
>    php74-lint:
Will need to update GitHub as well

2022-04-29 03:26 UTC, mjangda commented
Since we still support 7.4, should we keep linting against both? The danger of removing PHP 7.4 lint is that we may add something 8.0 specific and cause problems.

2022-04-29 04:58 UTC, sjinks commented
@mjangda we do check compatibility issues for PHP 7.4+. The issue is that the latest stable version of the PHPCompatibility ruleset does not check for PHP 8-specific keywords (it does not catch `class Match {}`, for example). This is why we are switching the base image to PHP 8.0: `php -l` will catch syntax errors specific to PHP 8.

In brief, PHP 8 catches syntax errors and phpcs continues to identify compatibility issues for all PHP versions since 7.4.

2022-04-29 05:01 UTC, sjinks commented on .circleci/config.yml
>    php74-lint:
Done.

Removed `ci/circleci: php74-lint` from the branch protection rules. Will need to add the renamed job once this is merged.

2022-04-29 20:10 UTC, rinatkhaziev approved these changes
🚀

2022-04-30 05:41 UTC, merged

2022-04-30 06:09 UTC, sjinks commented
r2470-stacks