Add Object Cache panel to Query Monitor
Automattic/vip-go-mu-plugins pull request #3150
Opened 2022-05-13 20:02 UTC by trepmal

## Description

Adds panel to Query Monitor that shows Object Cache stats. This the same data as currently shown in Debug Bar.

## Changelog Description

Show Object Cache stats to Query Monitor

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

Install and view:

![qm-object-cache](https://user-images.githubusercontent.com/251183/168381110-a5c406a7-fb7d-44aa-ad47-21c61d3d41e4.png)

Enable Debug Bar and notice "Memcache" item not shown while QM is active:

![debug-bar-no-cache](https://user-images.githubusercontent.com/251183/168381112-1196c555-1701-4e8f-a409-deae80a79537.png)

2022-05-13 21:09 UTC, rinatkhaziev commented
This makes me extremely happy

2022-05-14 08:42 UTC, sjinks requested changes
Looks awesome! I have left a few comments.

2022-05-14 08:42 UTC, sjinks commented on qm-plugins/qm-object-cache/qm-object-cache.php
> +	wp_enqueue_style( 'qm-objectcache-style', plugin_dir_url( __FILE__ ) . 'css/style.css', null, '0.1' );
A minor nitpick:

```suggestion
	wp_enqueue_style( 'qm-objectcache-style', plugin_dir_url( __FILE__ ) . 'css/style.css', array(), '0.1' );
```

According to the [documentation](https://developer.wordpress.org/reference/functions/wp_enqueue_style/), the third parameter is an array of strings, so let's keep it that way, please.

2022-05-14 08:42 UTC, sjinks commented on qm-plugins/qm-object-cache/class-qm-output-object-cache.php
> +		<div class="qm qm-non-tabular" id="<?php echo esc_attr( $this->collector->id() ); ?>">
I see that this `<div>` is not closed in this method. I just want to confirm that this is OK.

2022-05-14 08:42 UTC, sjinks commented on qm-plugins/qm-object-cache/qm-object-cache.php
> +	return $panels;
```suggestion
    $panels = array_filter( $panels, fn( $panel ) => ! is_a( $panel, Debug_Bar_Object_Cache::class ) );
    return array_values( $panels );
```

I won't insist on this change, though :-)

2022-05-14 16:37 UTC, trepmal commented on qm-plugins/qm-object-cache/class-qm-output-object-cache.php
> +		</div>
```suggestion
		</div>
		</div>
```

2022-05-14 16:49 UTC, sjinks approved these changes

2022-05-14 20:02 UTC, merged

2022-05-14 20:06 UTC, sjinks commented
r2491-stacks