Removing wp-parsely 2.6
Automattic/vip-go-mu-plugins pull request #3165
Opened 2022-05-17 15:34 UTC by pauarge

## Description

## Changelog Description

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

2022-07-20 12:46 UTC, pschoffer approved these changes

2022-07-20 12:51 UTC, pschoffer requested changes
Please update changelog text and test (mark tested) on local env

2022-07-21 08:34 UTC, pschoffer approved these changes
LGTM

2022-07-21 08:38 UTC, sjinks approved these changes

2022-07-21 08:39 UTC, merged