Removed the contingency for unprefixed environment variables
Automattic/vip-go-mu-plugins pull request #3169
Opened 2022-05-19 16:24 UTC by jesse-greathouse

## Description
Removes the use of unprefixed environment variables in the VIP mi-plugins

## Changelog Description

### Removed the retrieval of unprefixed VIP environment variables

VIP environment variables, enabled through the dashboard or CLI, will now always be prefixed with a VIP string. This will not affect the use of environment variables currently used, but aims to prevent collisions between VIP environment variables and constants that may be defined elsewhere.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test
1. Check out PR.
1. Define a constant in wp-config like `define('MY_CONSTANT', 'foo');`
1. Define an environment variable with the same name, through the dashboard or VIP CLI: `MY_CONSTANT = 'bar'`
1. echo the constant in the code like: `echo MY_CONSTANT`.
2. verify the environment variable did not change the constant to 'foo'

2022-05-19 16:37 UTC, sjinks approved these changes

2022-05-19 16:45 UTC, chriszarate submitted a review, later dismissed
This looks good, but please hold on deploying. There is an accompanying GOOP change and we also need to triple-check that other customers are not relying on the legacy behavior anymore. Thanks!

2022-06-22 22:12 UTC, chriszarate commented
@jesse-greathouse This is ok to be deployed. (It was actually always ok to deploy. It doesn't have any effect or dependency on whether the unprefixed constant is defined, which is done in GOOP.)

2022-06-25 00:14 UTC, sjinks requested changes
Could you please take a look at the failing tests?

2022-08-09 18:06 UTC, rinatkhaziev commented
@jesse-greathouse this is getting a bit stale. Can we please get it over the finish line?

2022-08-09 18:49 UTC, jesse-greathouse commented
Opened a new PR #3498

2022-08-09 18:49 UTC, closed without merging