Search: Queue class - Rename $object_type to $indexable_slug and throw error if queue_object() has invalid second parameter
Automattic/vip-go-mu-plugins pull request #3228
Opened 2022-06-06 19:50 UTC by rebeccahum

## Description
This PR:
- In `class-queue.php`, `$object_type` is renamed to `$indexable_slug` for better clarity 
- In `queue_object()`, a `WP_Error` will be thrown if it is called with an invalid indexable slug. This solves the issue if `$index_version` returns a `WP_Error`, it won't get converted to `0` from `$wpdb->prepare()`

## Changelog Description

### Plugin Updated: Enterprise Search

Rename `$object_type` to `$indexable_slug` and throw error if `queue_object()` has invalid second parameter

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test
1) Shell in and do:
```
$es = \Automattic\VIP\Search\Search::instance();
$es->init();

$es->queue->queue_object( 999, 'foo' );
```
2) Expect to see a `WP_Error` returned:
```
=> object(WP_Error)#4119 (3) {
  ["errors"]=>
  array(1) {
    ["invalid-indexable"]=>
    array(1) {
      [0]=>
      string(32) "Indexable not found for type foo"
    }
  }
  ["error_data"]=>
  array(0) {
  }
  ["additional_data":protected]=>
  array(0) {
  }
}
```

2022-06-06 20:12 UTC, rinatkhaziev commented on search/includes/classes/class-queue.php
> +	public function get_index_version_number_from_options( $indexable_slug, $options = array() ) {
This method misses arguments PHPDoc, let's add, since we're here.

2022-06-06 20:13 UTC, rinatkhaziev commented on search/includes/classes/class-queue.php
> +	public function count_jobs( $status, $indexable_slug = 'post', $options = array() ) {
Let's add PHPDoc here too.

2022-06-06 20:13 UTC, rinatkhaziev commented on search/includes/classes/class-queue.php
> +	public function count_jobs_due_now( $indexable_slug = 'post' ) {
and here

2022-06-06 20:13 UTC, rinatkhaziev commented on search/includes/classes/class-queue.php
> +	public function get_next_job_for_object( $object_id, $indexable_slug, $options = array() ) {
and here :)

2022-06-06 20:14 UTC, rinatkhaziev requested changes
Left a few ~notes~ nags :)

2022-06-07 14:53 UTC, rinatkhaziev commented on search/includes/classes/class-queue.php
> +	public function get_next_index_time( $object_id, $indexable_slug, $options = array() ) {
Missing `@param $options`

2022-06-07 14:55 UTC, rinatkhaziev commented on search/includes/classes/class-queue.php
> +	 * @return int $next_index_time The soonest unix timestamp when the object can be indexed again
looking at the code, the return value can be either int or null

2022-06-09 15:51 UTC, rinatkhaziev approved these changes
Thank you!

2022-06-09 21:59 UTC, merged

2022-06-14 20:24 UTC, sjinks commented
v20220614.1