Do not hardcode JetPack IPs
Automattic/vip-go-mu-plugins pull request #3297
Opened 2022-06-26 00:57 UTC by sjinks

## Description

This PR fixes SonarCloud's complaints about the hardcoded IP addresses we use in `vip_is_jetpack_request()`. Instead of hardcoding those IPs, we retrieve them from the [official endpoint](https://jetpack.com/support/how-to-add-jetpack-ips-allowlist/). We cache the list using Transients API and periodically update it using WP Cron.

Fixes: #1563

## Changelog Description

### Plugin Updated: VIP Helpers

Do not hardcode JetPack IPs; instead, retrieve them from the official API endpoint.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

The CI should pass.

2022-06-26 01:03 UTC, sjinks commented on vip-helpers/vip-utils.php
> -		'195.234.108.0/22',
These IPs come from the JSON.

2022-06-26 01:03 UTC, sjinks commented on vip-helpers/vip-utils.php
> -		'192.0.102.95/32',
These ones belong to the 192.0.96.0/20 range.

I assume it is safe to remove them?

2022-06-27 07:40 UTC, pschoffer commented
Looks smart to me, but I don't really understand that JP flow. @rinatkhaziev , @rebeccahum , @WPprodigy do you have an input on this one?

2022-06-27 19:11 UTC, rinatkhaziev requested changes
I don't think that using object cache is a good strategy here - since it may fall off at any given moment. Probably it's better to store as an autoloader option. The IPs don't change often.

2022-06-27 19:49 UTC, WPprodigy commented
I agree regarding saving as an option, but also could strip out the cron job even as it seems a little overkill IMO.

```
$option = get_option( 'option_name', [ 'data' => [], expiration => 0 ]  );

if ( empty( $option['data'] ) || $option['expiration'] < time() ) {
  $IPs = wp_remote_request();
  update_option( 'option_name',  [ 'data' => $IPs, expiration => time() + DAY_IN_SECONDS ] );
}

return $option['data'];
```

2022-06-27 19:52 UTC, rinatkhaziev commented
@WPprodigy what happens when your approach fails due to a network connectivity issue?

2022-06-27 21:53 UTC, WPprodigy commented
We don't need to update the option unless the remote request worked. Should always fall back to just returning from the data from the option.

2022-06-28 00:55 UTC, sjinks commented
@WPprodigy if we do requests in the foreground, won't it negatively affect load times?

2022-06-28 01:44 UTC, rinatkhaziev commented
> We don't need to update the option unless the remote request worked. Should always fall back to just returning from the data from the option.

Ok but imagine a scenario where option is missing and the request has failed, how would that potentially affect a request?

2022-06-28 02:13 UTC, WPprodigy commented
So before we ever have the chance to have a successful request? Could only ever happen early on in an app's lifecycle, and I mean, that's doomed either way if we can never get the list in the first place. So if the request fails then the option's IP list remains empty and `vip_is_jetpack_request()` will just have to return `false` to be safe.

> if we do requests in the foreground, won't it negatively affect load times?

Could swap it to doing the lookup/option update on `shutdown` if it's expired. So the current request will use the existing list and on shutdown it'll check if it needs to update. Ultimately not that different from cron, I'm just pretty opposed to an entirely new cron job for such a tiny task.

2022-06-28 15:55 UTC, nickdaugherty commented on vip-helpers/class-jetpack-ip-manager.php
> +class JetPack_IP_Manager {
Jetpack has a lowercase P ... `_lowercase_p_dangit()`! 😄

2022-06-30 14:52 UTC, sjinks commented
I went with the mixed approach way.

2022-06-30 19:08 UTC, WPprodigy submitted a review, later dismissed
Thanks for the changes, looks good!

2022-07-01 19:23 UTC, rinatkhaziev requested changes
Thoughts on actually not doing it on the shutdown but rather just checking at the call site (vip_is_jetpack_request)? Since this is only needed for machines to talk to each other tacking 50ms+ on random requests seems to be a bit much?

2022-07-01 22:13 UTC, WPprodigy commented
Pretty sure it is only triggered at the call site still.

2022-07-02 08:30 UTC, sjinks commented
Done but as far as I can tell, the only change is that we refresh the IPs right when `vip_is_jetpack_request()` is called vs we deferred the update until `shutdown`.

2022-07-02 09:40 UTC, WPprodigy commented
I kinda liked the deferred version, but tbh probably doesn't make any notable difference to justify the complexity increase.

I would however still consider having the `wp_cache_add()` lock, to prevent a possible stampede of requests all trying to refresh the option at the same time.

2022-07-05 21:34 UTC, rinatkhaziev approved these changes

2022-07-05 21:44 UTC, merged