Add slack hook to the CI pipeline
Automattic/vip-go-mu-plugins pull request #3397
Opened 2022-07-18 11:28 UTC by pschoffer

2022-07-18 15:28 UTC, rebeccahum requested changes

2022-07-18 15:28 UTC, rebeccahum commented on .github/workflows/changelog-summary.yml
> +      - update/ci
I think we removed this branch, did this accidentally sneak in? 🙂

2022-07-19 06:56 UTC, pschoffer commented on .github/workflows/changelog-summary.yml
> +      - update/ci
Damn, I thought I would get away with keeping my test branch in there ... I need a higher Sneak level clearly. I can remove it again ... till the next time:)

2022-07-19 06:57 UTC, pschoffer commented on .github/workflows/changelog-summary.yml
> +      - update/ci
Done

2022-07-19 07:01 UTC, sjinks approved these changes

2022-07-19 12:33 UTC, merged