add vip admin notice filter
Automattic/vip-go-mu-plugins pull request #3678
Opened 2022-09-22 17:46 UTC by davidsword

Make it easier to conditionally not show specific VIP admin notices.

Useful for anyone wanting to dynamically suppress our messages for certain caps, or any other reason. Ex:

```php
add_filter('vip_admin_notice_hide_php8-migrations-3', function($show) {
	return ! is_super_admin();
});
```

Might be better to have just `vip_hide_admin_notice` to blanket hide all VIP admin_notices instead of finding the ID for each new message.

## Description

## Changelog Description

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

2022-09-22 18:33 UTC, sjinks requested changes

2022-09-22 18:33 UTC, sjinks commented on admin-notice/class-admin-notice-controller.php
> +			$is_hidden_with_filter = apply_filters('vip_admin_notice_hide_'.$notice->dismiss_identifier, false);
```suggestion
			$is_dismissed          = in_array( $notice->dismiss_identifier, $dismissed_notices );
			$is_hidden_with_filter = apply_filters( 'vip_admin_notice_hide_' . $notice->dismiss_identifier, false );
```

to keep phpcs happy

2022-09-22 20:24 UTC, rebeccahum commented
Given that the notices usually only display important information, I'm not sure we really want to grant the capability to dynamically disable them. 🙂 Especially if the notices have a [Capability_Condition ](https://github.com/Automattic/vip-go-mu-plugins/blob/develop/admin-notice/conditions/class-capability-condition.php) tied to them, then we definitely wouldn't want that overwritten.

2022-10-01 03:45 UTC, mjangda commented
Going to close this as #wontfix per @rebeccahum's note. We do need to be mindful of the capability we use (will likely default to is_super_admin() moving forward) and other more impactful ways to surface this information.

2022-10-01 03:45 UTC, closed without merging