VIP Request Block: Add function to allow for blocking by partial User Agent string.
Automattic/vip-go-mu-plugins pull request #4001
Opened 2022-12-30 19:07 UTC by mslinnea

## Description
I would like to block requests by a partial match on the user agent string.  The use case is a User Agent header like 'WordPress/6.1.1; https://www.example.com' which is the default format of a User Agent string to WordPress.  If I block by exact match, as soon as WordPress is upgraded, this exact match will no longer work.  

## Changelog Description

Adds VIP_Request_Block::ua_partial_match

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

Outline the steps to test and verify the PR here.

Example:

1. Check out PR.
1. Follow documentation in https://docs.wpvip.com/how-tos/block-requests/ to test, except use `VIP_Request_Block::ua_partial_match` with a substring instead of `VIP_Request_Block::ua`

2023-01-02 14:32 UTC, sjinks requested changes

2023-01-02 14:32 UTC, sjinks commented on lib/class-vip-request-block.php
> +		if ( isset( $_SERVER['HTTP_USER_AGENT'] ) && str_contains( $_SERVER['HTTP_USER_AGENT'], $user_agent_substring ) ) {
`str_contains()` appeared in PHP 8; we still need to be compatible with PHP 7.4. Could you please update the code to use `strpos()` or whatever is appropriate?

Thank you!

2023-01-05 22:04 UTC, rebeccahum commented
@sjinks I committed the changes on behalf.

2023-01-05 22:44 UTC, sjinks commented
@rebeccahum thank you, I will take a closer look tomorrow - I see SonarCloud complains etc.

2023-01-05 23:50 UTC, GaryJones commented
It's suggesting that [this line](https://github.com/Automattic/vip-go-mu-plugins/pull/4001/files?w=1#diff-2aaa18fe2bb071a15fb049eb6bc4dcf92755b5f1baa6171d13e26330f629b38fR93) should be `static::block_and_log()` and not `self::block_and_log()` - i.e. make use of late static binding (PHP 5.3) to reference any child class that may have extended this class which may overwrite `block_and_log()`. 

Same fix will be needed in at least one other method too.

2023-01-06 18:11 UTC, sjinks approved these changes

2023-01-06 18:12 UTC, merged