Revert "Reverting wp-cli-db"
Automattic/vip-go-mu-plugins pull request #4111
Opened 2023-02-09 19:57 UTC by rebeccahum

Reverts Automattic/vip-go-mu-plugins#3683

Previously, this broke the `import` command on dev-env:
```
Uncaught Exception: The db command is not currently supported in this environment. in /wp/wp-content/mu-plugins/lib/helpers/wp-cli-db/class-config.php:38
```

But it looks like that's not the case anymore:
```
╰─$ vip dev-env --slug es-site import sql ~/Downloads/test.sql
...
Success: Database imported.
```

## Changelog Description

### Plugin added: WP-DB-CLI
Previously reverted, this reverts that change and adds back `/lib/helpers/wp-cli-db.php`

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out PR.
2. On Local dev-env, attempt to import `vip dev-env import sql ~/Downloads/test.sql` and expect no exception

2023-02-09 21:14 UTC, rinatkhaziev requested changes
We first should check there are no more envs being spun up on the VIP-CLI version that had the error. If there are we can't really merge this.

2023-02-10 00:48 UTC, sjinks commented
I offer that we add a check whether the code runs in a dev env (if I am not mistaken, we had a constant for that). If it does, we should not disable `wp db` commands, and import will work for those old clients.

2023-02-10 17:11 UTC, rebeccahum commented
The problem with that approach is that `000-pre-vip-config` is loaded before the constants are set, so we'd need to move the constants to load then. I'm not sure how I feel about getting the constants to load beforehand in case it's already been defined without a check in `vip-config.php` causing for fatals.

2023-02-10 18:25 UTC, rinatkhaziev commented
@rebeccahum I'd argue those 4 constants are internal so whoever is defining them in vip-config.php is "holding it wrong'

2023-02-10 18:36 UTC, rinatkhaziev commented
Well apparently there's are quite a few instances of defining  it, so maybe it's me who's holding it wrong 😅

2023-02-11 06:22 UTC, rebeccahum commented
OK, tested on VIP-CLI 2.11 and it works now.

2023-02-14 16:04 UTC, rinatkhaziev approved these changes

2023-02-14 16:18 UTC, merged