Jetpack: Removed unneeded versions
Automattic/vip-go-mu-plugins pull request #4129
Opened 2023-02-16 18:22 UTC by luiztiago

## Description

Removing Jetpack 9.4 and 9.8 fallback versions, because we don't have support with Wordpress 5.6 and 5.7

2023-02-16 18:24 UTC, rebeccahum submitted a review, later dismissed
🧨

2023-02-16 20:18 UTC, rinatkhaziev requested changes
As discussed in Slack this contains one extra condition, since we only have 5.8 and above the first condition should be

```if ( version_compare( $wp_version, '5.9', '<' ) ) {```
for all sites less than 5.9 set default as 10.9

But maybe we should use this PR to rework the whole block to be easier testable and less confusing by abstracting this as a function which we can write tests for.

2023-02-16 21:19 UTC, luiztiago commented
> As discussed in Slack this contains one extra condition, since we only have 5.8 and above the first condition should be
> 
> `if ( version_compare( $wp_version, '5.9', '<' ) ) {` for all sites less than 5.9 set default as 10.9
> 
> But maybe we should use this PR to rework the whole block to be easier testable and less confusing by abstracting this as a function which we can write tests for.

Totally agree. The logic is not easy to understand at first time, with some code pranks. Now we have a lower quantity of Jetpack versions and I think the key/value usage would not help to get the code (because we'll keep with pranks such as `{ "5.9": "10.9" }`, without including 5.9.x versions).

I researched a bit and I think the comments on this case should help us to don't add code complexity and have good readability.

```js
if ( ! defined( 'VIP_JETPACK_DEFAULT_VERSION' ) ) {
	if ( version_compare( $wp_version, '5.9', '<' ) ) {
		// Wordpress 5.8.x and older. Not including 5.9.
		define( 'VIP_JETPACK_DEFAULT_VERSION', '10.9' );
	} elseif ( version_compare( $wp_version, '6.0', '<' ) ) {
		// Wordpress 5.9.x and newer. Not including 6.0.
		define( 'VIP_JETPACK_DEFAULT_VERSION', '11.4' );
	} else {
		// Wordpress 6.0 and newer
		define( 'VIP_JETPACK_DEFAULT_VERSION', '11.8' );
	}
}
```

Other than that, tests are always good to be added. 🧶

2023-02-17 15:49 UTC, rinatkhaziev commented on tests/test-jetpack.php
> +			'5.9.0' => '11.4',
WordPress doesn't exactly follow semver, so the versions would be like 5.9, 5.9.1 ,etc
```suggestion
			'5.9' => '11.4',
```

2023-02-23 16:50 UTC, rinatkhaziev commented on tests/test-jetpack.php
> +		foreach ( $versions_map as $wordpress_version => $jetpack_version ) {
@sjinks will overwriting the global potentially mess up other tests?

2023-02-23 16:53 UTC, rinatkhaziev commented on jetpack.php
> +		// Wordpress 5.8.x and older. Not including 5.9.
```suggestion
		// WordPress 5.8.x and older. Not including 5.9.
```

2023-02-23 16:53 UTC, rinatkhaziev commented on jetpack.php
> +		// Wordpress 5.9.x and newer. Not including 6.0.
```suggestion
		// WordPress 5.9.x and newer. Not including 6.0.
```

2023-02-23 16:54 UTC, rinatkhaziev commented on jetpack.php
> +		// Wordpress 6.0 and newer
```suggestion
		// WordPress 6.0 and newer
```

2023-02-23 17:55 UTC, rebeccahum commented on tests/test-jetpack.php
> +		foreach ( $versions_map as $wordpress_version => $jetpack_version ) {
Might be best practice anyways to reset it back after the test is done for clean up?

2023-02-24 16:37 UTC, rinatkhaziev commented on tests/test-jetpack.php
> +		foreach ( $versions_map as $wordpress_version => $jetpack_version ) {
@luiztiago can you address this please? and then this is good to go

2023-02-27 23:25 UTC, rebeccahum commented on tests/test-jetpack.php
> +		foreach ( $versions_map as $wordpress_version => $jetpack_version ) {
@rinatkhaziev @luiztiago Addressed ahead of tmrw's release.

2023-02-27 23:31 UTC, luiztiago commented on tests/test-jetpack.php
> +		foreach ( $versions_map as $wordpress_version => $jetpack_version ) {
Thanks @rebeccahum 🚀

2023-02-28 00:12 UTC, rinatkhaziev approved these changes

2023-02-28 00:16 UTC, merged