Search: Add CLI command `wp vip-search health stop-validate-contents`
Automattic/vip-go-mu-plugins pull request #4244
Opened 2023-03-17 02:58 UTC by rebeccahum

## Description
Would be nice to have a killswitch for the validate-contents CLI command since it can eat up a lot of resources.

## Changelog Description

### Plugin Updated: Enterprise Search

Added CLI command `stop-validate-contents` to stop any validate_contents processing.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

2023-03-22 15:25 UTC, rinatkhaziev commented on search/includes/classes/class-health.php
> +			$should_stop = get_transient( self::STOP_VALIDATE_CONTENTS_TRANSIENT );
Are we sure that `get_transient` is the right approach here? Since it's a wrapper around `$value = wp_cache_get( $transient, 'transient' );` it'll just stay in memory.

https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/option.php#L876-L878

Additionally, shouldn't it be in the do/while block above?  I.e. check that on every batch.

2023-03-22 15:26 UTC, rinatkhaziev requested changes
Left some inline comments

2023-03-22 16:07 UTC, rebeccahum commented on search/includes/classes/class-health.php
> +			$should_stop = get_transient( self::STOP_VALIDATE_CONTENTS_TRANSIENT );
It is already in the do/while block above 🙂 . Is there another one I'm missing?

Re: using a transient, what do you recommend instead? An option for better longevity?

2023-03-23 15:42 UTC, rinatkhaziev commented
Thanks for the changes, the other thing i noticed is that some of the error codes. have `es_` prefix and others don't. Can we tidy this up as a part of this PR?

2023-03-24 17:07 UTC, rinatkhaziev approved these changes

2023-03-24 17:32 UTC, merged