tests: Fix `expectException()` usage
Automattic/vip-go-mu-plugins pull request #4464
Opened 2023-05-16 11:58 UTC by sjinks

When we `expectException()`, the code that follows the statement that throws an exception, does not run.

For example,

```php
$this->expectException( \Exception::class );

$actual_result = Vary_Cache::register_groups( [
	'dev-group',
	'design-group',
] );

$this->assertFalse( $actual_result, 'register_groups after send_headers did not return false' );
$this->assertEquals( [], Vary_Cache::get_groups(), 'Registered groups are not empty.' );
```

`Vary_Cache::register_groups()` spits a warning that gets converted into an `Exception` (we do this with our custom error handler; PHPUnit employs a similar technique). Assertions that follow `Vary_Cache::register_groups()`, are not run.

The same thing happens here:

```php
function send_visibility_headers( $file_visibility, $file_path ) {
	// ...
	switch ( $file_visibility ) {
		// ...
		default:
			trigger_error( sprintf( 'Invalid file visibility (%s) ACL set for %s', $file_visibility, $file_path ), E_USER_WARNING );
			break;
	}

	http_response_code( $status_code );

	if ( null !== $is_private ) {
		$private_header_value = $is_private ? 'true' : 'false';
		header( sprintf( 'X-Private: %s', $private_header_value ) );
	}
}
```

```php
	public function test__send_visibility_headers__invalid_visibility() {
		$this->expectException( \Exception::class );
		$this->expectExceptionMessage( 'Invalid file visibility (NOT_A_VISIBILITY) ACL set for /wp-content/uploads/invalid.jpg' );

		send_visibility_headers( 'NOT_A_VISIBILITY', '/wp-content/uploads/invalid.jpg' );

// The checks below will not run:
		$this->assertEquals( 500, http_response_code(), 'Status code does not match expected' );

		$headers = headers_list();
		$this->assertNotContains( 'X-Private: true', $headers, 'Sent headers include X-Private: true header but should not.', true );
		$this->assertNotContains( 'X-Private: false', $headers, 'Sent headers include X-Private:false header but should not.', true );
	}
```

When the code spits a warning that we convert to an exception, no code that follows the guilty statement is run; in this case, we leave the function right after `trigger_error()`; no headers are sent.

2023-05-19 14:10 UTC, rebeccahum requested changes
Just left one comment on one thing I don't fully understand.

Also, I'm wondering if we need to figure out a different way to test for the ones we've removed after the `expectException()`.

2023-05-19 14:10 UTC, rebeccahum commented on tests/files/acl/test-acl.php
> +			self::assertTrue( false );
I'm not sure what this is doing exactly.

2023-05-19 14:25 UTC, sjinks commented on tests/files/acl/test-acl.php
> +			self::assertTrue( false );
This code makes sure that `maybe_load_restrictions();` spits a warning (that gets converted into an exception by our helper error handler). If exception is not thrown, `assertTrue( false )` makes the test fail. This tests the case when `maybe_load_exception()` runs without warnings.

2023-05-19 14:48 UTC, rebeccahum commented on tests/files/acl/test-acl.php
> +			self::assertTrue( false );
Can we just add a comment there for future reference to why we are doing it this way? Makes sense now, thank you!

2023-05-19 14:48 UTC, rebeccahum commented on tests/files/acl/test-acl.php
> +			self::assertTrue( false );
Also in #4463 too

2023-05-26 20:37 UTC, rebeccahum approved these changes

2023-05-26 20:57 UTC, merged