Remove vaultpress ad from jetpack page
Automattic/vip-go-mu-plugins pull request #4956
Opened 2023-10-19 03:43 UTC by aswasif007

## Description

## Changelog Description

We are removing VaultPress ad from the Jetpack page, as we do not use VaultPress for VIP sites anymore.

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation). 

## Steps to Test

2023-10-25 12:28 UTC, saroshaga commented
Can we test this on a test site: https://fieldguide.automattic.com/vip-go/mu-plugins-upgrades-on-vip-go/#custom-branches?

2023-10-26 19:38 UTC, WPprodigy requested changes
Let's only run this when really necessary, and also add some safeguards (I've been burned too many times 😅)

Something like:

```
add_action( 'admin_init', function() {
	if ( wp_doing_ajax() || ! method_exists( 'Jetpack', 'connection' ) || ! defined( 'WPCOM_VIP_MACHINE_USER_LOGIN' ) ) {
		return;
	}

	$jp_connection = Jetpack::connection();
	if ( method_exists( $jp_connection, 'get_connection_owner' ) ) {
		$connection_owner  = $jp_connection->get_connection_owner();
		$is_vip_connection = isset( $connection_owner->user_login ) && WPCOM_VIP_MACHINE_USER_LOGIN === $connection_owner->user_login;

		if ( $is_vip_connection ) {
			add_filter( 'jetpack_my_jetpack_should_initialize', '__return_false' );
		}
	}
} );
```

2023-10-27 07:52 UTC, aswasif007 commented
@WPprodigy How do I fix the code coverage issue?

2023-10-27 08:05 UTC, aswasif007 commented
@saroshaga Deployed for this site: https://admin.wpvip.com/#/applications/7299/wasif-singlesite-test.go-vip.net

2023-10-31 13:41 UTC, aswasif007 commented
Running it on `admin_init` didn't fix the issue. Running on `plugin_loaded` instead.

2023-10-31 14:36 UTC, rebeccahum commented
@aswasif007 Don't worry about the codecov/patch issue.

2023-10-31 17:34 UTC, WPprodigy approved these changes

2023-10-31 18:32 UTC, merged