Prevent enabling debug mode on local env
Automattic/vip-go-mu-plugins pull request #5341
Opened 2024-03-18 04:23 UTC by aswasif007

## Description

We are updating the code to prevent debug mode from enabling automatically on local env.

## Changelog Description

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation). 

## Steps to Test

2024-03-18 04:24 UTC, aswasif007 commented
I am not sure if this has other implications. @Automattic/vip-platform-cantina please advise!

2024-04-08 23:03 UTC, rebeccahum commented
@aswasif007 Per the BB8 comments, we shouldn't be removing this entirely locally, but only forcing it for users logged in locally I think.

2024-07-10 18:59 UTC, rinatkhaziev requested changes
Needs further consideration.

2024-11-12 17:59 UTC, WPprodigy commented
It's a handy feature to be able to get QM for logged out requests. I don't think we should take that away. But at the same time, I agree that we shouldn't start QM for logged out by default since that's not normal behavior.

Maybe should be this instead:

```
if ( $is_nocache && $is_debug && ( $is_proxied || $is_local ) ) {
```

2025-01-20 00:17 UTC, closed without merging