2FA: Add pattern to validate phone number format as per E.164
Automattic/vip-go-mu-plugins pull request #5538
Opened 2024-05-03 05:44 UTC by saroshaga

## Description

The SMS provider that the two-factor authentication plugin uses rejects any phone number that isn't in [E.164 standards](https://www.twilio.com/docs/glossary/what-e164).

Here we're applying some client-side validation using HTML to ensure that incorrect phone numbers aren't configured.

## Changelog Description

### Changed

- WPCOM VIP 2FA: Add pattern to validate phone number format as per E.164

## Pre-review checklist

- [ ] This change works and has been tested locally or in Codespaces (or has an appropriate fallback).
- [ ] This change works and has been tested on a sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation). 

## Steps to Test

1. Check out PR.
1. Go to `wp-admin` > `Tools` > `Bakery`
1. Click on "Bake Cookies" button.
1. Verify cookies are delicious.

2024-05-06 14:30 UTC, brunobasto approved these changes
Looks good to me! Thank you for handling this!

2024-05-08 20:49 UTC, rebeccahum approved these changes

2024-05-08 21:02 UTC, rebeccahum requested changes
Hmm, I just tested this and it's still accepting phone numbers such as 780-123-4567

2024-07-09 01:20 UTC, sjinks requested changes

2024-07-09 01:20 UTC, sjinks commented on wpcom-vip-two-factor/sms-provider.php
> +						pattern="^\+[1-9]\d{1,14}$"
> ITU-T specifies that a phone number cannot be longer than fifteen digits, with one to three digits reserved for the country calling code, but valid numbers in Germany have been assigned that are longer than this.
>
> -- https://github.com/google/libphonenumber/blob/master/FALSEHOODS.md

2025-03-28 03:33 UTC, mjangda commented
@andrea-sdl how did we solve this for VIP Auth? Can we implement similar validation here?

2025-03-28 10:14 UTC, andrea-sdl commented
@mjangda for VIP Auth we used https://github.com/jackocnr/intl-tel-input on the frontend, and then validated the phone number via the Twilio API https://github.com/Automattic/vip-auth/blob/d414a80f657954c84026d7fe9dd4799d423ee6be/client-mu-plugins/vip-auth/src/mfa/providers/class-sms.php#L75

2025-06-17 00:19 UTC, closed without merging