Add VIP_GO_APP_ID to telemetry event data
Automattic/vip-go-mu-plugins pull request #5922
Opened 2024-10-11 17:36 UTC by alecgeatches

## Description

This PR extends the recent Tracks telemetry work (https://github.com/Automattic/vip-go-mu-plugins/pull/5869, https://github.com/Automattic/vip-go-mu-plugins/pull/5921) to include VIP app IDs in a separate field on events. We already utilize app IDs for user identification:

https://github.com/Automattic/vip-go-mu-plugins/blob/7508ea94d7fdaecf603a73ac46fb36fdd8829560/telemetry/tracks/class-tracks-event.php#L206-L214

This tracks `userids` with values in the format `{{site_id}}_{{wp_user_id}}`. This is less useful for tracking per-app events, since we'd require parsing and preprocessing event data. This PR serves to explicitly track app IDs in a separate data point to make filtering easier. Note that we already track [the app environment](https://github.com/Automattic/vip-go-mu-plugins/blob/7508ea94d7fdaecf603a73ac46fb36fdd8829560/telemetry/tracks/class-tracks-event.php#L156-L162) (e.g. `local`/`develop`) as well as [organization ID](https://github.com/Automattic/vip-go-mu-plugins/blob/7508ea94d7fdaecf603a73ac46fb36fdd8829560/telemetry/tracks/class-tracks-event.php#L164-L170), so this fits right in.

## Changelog Description

### Changed

- Added `VIP_GO_APP_ID` to Tracks telemetry events

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally or in Codespaces (or has an appropriate fallback).
- [ ] This change works and has been tested on a sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation). 

## Steps to Test

Run unit tests:

```bash
./bin/test.sh --filter Tracks_Event_Test
```

2024-10-11 17:37 UTC, alecgeatches commented
I branched these changes from https://github.com/Automattic/vip-go-mu-plugins/pull/5921, so probably best to merge those first.

2024-10-11 18:34 UTC, mjangda commented
> We already utilize app IDs for user identification

Should we just remove that block? On VIP, the user id should be set based on the hashed email (the VIP_TELEMETRY_SALT block above).

2024-10-11 19:00 UTC, mjangda requested changes
Left some suggestions on this.

It would be nice to cleanup the other props as well (i.e. change any references of `vipgo_` to `vip_` (e.g. `vipgo_env`), although I realize that is increasing the scope of this PR :)

Separately, what do you think about adding the home or site URL as a prop? (`vip_home_url`). The ID is helpful, but the URL would make sorting through data easier.

2024-10-11 19:00 UTC, mjangda commented on telemetry/tracks/class-tracks-event.php
>  				$event->vipgo_org = $org_id;
Similar to the app change, let's rename this:

```suggestion
				$event->vip_org_id = $org_id;
```

2024-10-11 19:00 UTC, mjangda commented on telemetry/tracks/class-tracks-event.php
> +				$event->vipgo_app = $app_id;
The constant is incorrectly named :(

Let's rename the prop to `vip_env_id`: 

- remove `go`
- replace `app` with `env`
- add `_id`

```suggestion
			// APP_ID is incorrectly named; it actually references the environment ID
			$env_id = constant( 'VIP_GO_APP_ID' );
			if ( is_integer( $env_id ) && $env_id > 0 ) {
				$event->vip_env_id = $env_id;
```

2024-10-15 00:28 UTC, sanmai commented on tests/telemetry/tracks/test-class-tracks-event.php
> +		$this->assertSame( self::VIP_GO_APP_ID, $event->get_data()->vipgo_app );
```suggestion
		$this->assertSame( self::VIP_GO_APP_ID, $event->get_data()->vip_env_id );
```

2024-10-15 00:29 UTC, sanmai commented on telemetry/tracks/class-tracks-event-dto.php
> +	public int $vipgo_app;
```suggestion
	public int $vip_env_id;
```

2024-10-15 00:33 UTC, sanmai commented on telemetry/tracks/class-tracks-event.php
> +		// Set VIP app ID if it exists.
```suggestion
		// Set VIP environment ID if it exists.
```

2024-10-15 00:38 UTC, sanmai approved these changes
It sounds like we addressed all @mjangda's suggestions.

2024-10-15 00:46 UTC, sanmai commented
WP nightly tests are broken, probably unrelated to this PR.

2024-12-16 20:35 UTC, alecgeatches commented
It appears these changes were wrapped into the work in #5990 and #5966, [see discussion](https://github.com/Automattic/vip-go-mu-plugins/pull/5966/files#r1841536378). Closing!

2024-12-16 20:35 UTC, closed without merging